name: Deploy Storage

on:
  push:
    branches:
      - master
    paths:
      - "storage/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Test
        env:
          JWT_SECRET: jwt_secret_for_tests
          MONGO_DB_CONN_STRING: not_used_in_tests
        run: |
          cd storage/
          npm install
          npm run test:ci

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: depl-storage
          FOLDER: storage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Storage tested and deployed"
