name: Deploy Daemonic-Bots

on:
  push:
    branches:
      - master
    paths:
      - "daemonic-bots/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Test
        env:
          MONGO_DB_CONN_STRING: not_used_in_tests
          KOVAN_RPC: not_used_in_tests
          MUMBAI_RPC: not_used_in_tests
        run: |
          cd daemonic-bots/
          npm install
          npm run test:ci

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: depl-daemonic-bots
          FOLDER: daemonic-bots
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Daemonic-bots tested and deployed"
